### ISSUE TITLE
'Watch with me' share button

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#111]
We've been asked to add the ability to share programs so friends can send the link and watch together.

I imagine that dynamically creating a permalink for each listing (or time slot?) is a large lift. Let me know if it's not, though!

**Comment by mstem** [comment]
SVG https://www.dropbox.com/s/j1mrwjz1wccoia7/noun_Share_3233417.svg?dl=0
![noun_Share_3233417](https://user-images.githubusercontent.com/613432/84522006-290e4000-acd6-11ea-9c0b-90d9b746718b.png)

**Comment by jjandoc** [comment]
So a few issues to bring up here. It's easy enough to add a share link that generally shares the liveguide. We do need to consider that there's three different contexts for this, and two of those contexts are iframe-d so we don't have control over the meta data that will actually show when shared.

Creating a permalink to a specific item in the grid isn't hard. The JSON feed from Google sheets supplies a unique id we can use for each entry we're displaying. But an item on the feed is only going to be valid for four hours so I wonder about the actual usefulness here. Another thing implementation detail is that for this to work we'd need some help from the boston.com and bostonglobe.com. If we want to link to a video with ID #123456, the page the liveguide is sitting on will need to pass through that ID, in other words bostonglobe.com/liveguide?id=123456 will need to show the iframed content at  globe--paquete.netliy.app/?id=123456. Not hard, but not something I can do on my end.

Finally I don't think we need to use sharethis.com. I haven't touched that in about eight years. It's not really necessary since the primary sharing channels these days have been narrowed down to Facebook, Twitter, and Email and it's usually easy to just do a straight implementation.

**Comment by mstem** [comment]
Thanks for helping think this through. 

The two Glob instances of the site already have our metadata tags on the pages. I'll see if they can update the share preview image on both. We should remember to implement the meta tags on our standalone version if we haven't already.

The requested use case is to let people ask their friends to watch a program with them in real-time. Let's test it on our standalone domain version of the app first, and see if it gets used before implementing on the other two? In order to do that (and in general), let's track events where the user clicks the share button.

I'll create a new issue to distinguish a general 'share liveguide' button from 'watch with friends'.

And we can drop sharethis.com - I clearly came of age in Web 2.0 and haven't stayed relevant! 

But I might suggest we add Whatsapp to the list of sharing options. Ideally on mobile we can just kick to the OS sharing menu.

Some sharing codes:

- [Whatsapp](https://stackoverflow.com/questions/21935149/sharing-link-on-whatsapp-from-mobile-website-not-application-for-android)
- Email: mailto
- Fbook: https://www.facebook.com/sharer/sharer.php?u=
- Twitter: https://twitter.com/intent/tweet?text=Seeing%20Red%3A%20A%20Boston%20Globe%20Spotlight%20Team%20report%20on%20traffic%20in%20Massachusetts%20-%20The%20Boston%20Globe&via=BostonGlobe&url=https://apps.bostonglobe.com/metro/investigations/spotlight/2019/11/19/seeing-red//boston-traffic-stuck-politics/

**Comment by jjandoc** [comment]
Cool, @margoyle do you have a particular set of social icon svgs for the above you'd want me to use?

**Comment by jjandoc** [comment]
As a first step to accomplishing this, I've set up deep linking in #118. If you check out https://deploy-preview-118--paquete.netlify.app/ and click around you'll see the URL updates. Also the back and forward browser buttons will navigate you through your history. If you refresh with an `id` param in the url you'll see that the correct video is featured and that it doesn't get randomly replaced after 15 seconds.
