### ISSUE TITLE
Share LiveGuide button

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#115]
General purpose share button to share the app's URL. Let's implement on all 3 versions of the app.

It would be great if on mobile it can kick to the OS share menu.

**Comment by mstem** [comment]
https://www.dropbox.com/s/j1mrwjz1wccoia7/noun_Share_3233417.svg?dl=0

**Comment by jjandoc** [comment]
Kicking to the OS share menu should be doable. Note to self, documentation on that [here](https://css-tricks.com/how-to-use-the-web-share-api/).

For the embedded versions of this, does boston.com and bostonglobe.com want to add any tracking parameters to the URL? Something like "https://www.bostonglobe.com/liveguide/?utm_source=share"?

**Comment by mstem** [comment]
Good question, will inquire

**Comment by jjandoc** [comment]
@mstem this is up for review here: https://deploy-preview-121--paquete.netlify.app/. Let me know if you have any feedback or if there are specific URL parameters i should add for the boston.com and bostonglobe.com variants. Environment variables are in place to share the appropriate link for each variant.

**Comment by mstem** [comment]
Thanks for the reminder. The functionality is great on Android. 

If this isn't the case already, it would be great if the three versions of the app share their own URL (boston.com/liveguide, bostonglobe.com/liveguide, and liveguide.us). I'm not sure we need other URL parameters - were you thinking so we can track that traffic?

On Android, it loads both the OS share menu and the 4 share buttons - is that intentional? Ideally it would just load the OS sharing menu in that context.

I'm also curious what you think about the share icon. Do you think the iOS share icon (https://www.iconfinder.com/icons/1902567/arrow_export_file_ios_material_share_icon) looks better?

Whichever we decide, the icon should be white, not black. LMK if you need me to change it.

**Comment by jjandoc** [comment]
Share's a tricky icon. I like the one we have now more than the iOS one, but I still don't think it's a _great_ one. I think the platform icons (Facebook and Twitter bird specifically) are usually a little clearer though even that can be confusing depending on context - are we sharing something or going to the organization's Facebook page? I think what we have now is the best of not great options, but let me double check to ensure that the proper hover title tag and whatnot are in place so we can at least give as many hints as possible to the user.

> Whichever we decide, the icon should be white, not black.

Is it not white for you? Interesting. Looks good to me, but let me double check on that with my test devices.

> On Android, it loads both the OS share menu and the 4 share buttons - is that intentional? Ideally it would just load the OS sharing menu in that context.

It was. I wasn't sure what the best thing to do for that was since I wanted to give non-native share options to the user if available but if you don't like it I can remove.
