### ISSUE TITLE
Auto-selection continues on Windows Firefox even when user has paused the scroll

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#130]
https://www.loom.com/share/433b38d8c5f24f4b9c97723d9878368f

To replicate,
Open the app in Firefox (https://www.bostonglobe.com/liveguide/)
Hit pause on the scroll
Click a program to watch (I tested it with an embedded video)
The app continues auto-selecting away from the video you're watching

**Comment by mclaros** [comment]
@mstem This should be fixed on production, assuming I understood correctly. I couldn't replicate it exactly on production since there were no events being shown at the time for me.

This issue was not specific to firefox. The bug was introduced with recent code, but it only affected users who did _not_ click on the event listing inside the events list/grid
