### ISSUE TITLE
Add podcast playing support in media pane

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#40]
We will have consistently formatted Stitcher embed data so we can include major podcasts in the listings. Could you add the logic to load the Stitcher embed player in the media pane (where the YouTube player loads)?

**Comment by mstem** [comment]
Twitcher embed code, with the episode URL as SRC:

`<iframe style="border: solid 1px #dedede;"  src="https://app.stitcher.com/splayer/f/159738/69466314" width="220" height="150" frameborder="0" scrolling="no"></iframe>`

**Comment by jjandoc** [comment]
How can I parse the episode url from the stream url? For instance, I see LeVar Burton reads has a url of https://app.stitcher.com/browse/feed/141202/episodes. That has the feed ID of 141202 but not the episode ID.

**Comment by mstem** [comment]
The player will always load the most recent episode, so it'll work with
just the stream URL

**Comment by jjandoc** [comment]
Cool, this is in place then.

**Comment by mstem** [comment]
It looks like the "Watch" button doesn't load the audio in the pane, but instead links to the Stitcher.com page - https://paquete.netlify.app/. Is there something we should be doing differently on the data side?

**Comment by jjandoc** [comment]
Okay, the issue is that I can't derive the embed URL from the one you just posted. The human-readable slug of "npr-programs-fresh-air-podcast" is not what I need for the embed URL. I actually need the show ID - so `5556` in the embed URL https://app.stitcher.com/splayer/f/5556. I think for Stitcher we're going to have to use the Embed Link column. You can grab the embed link from stitcher here:
![Screen Shot 2020-05-17 at 9 33 37 AM](https://user-images.githubusercontent.com/801206/82154318-d8640e00-9821-11ea-83c9-8f2845bbe32f.png)

**Comment by jjandoc** [comment]
I put this up on the demo data so you can see the inline player:
![Screen Shot 2020-05-17 at 9 32 47 AM](https://user-images.githubusercontent.com/801206/82154338-fa5d9080-9821-11ea-96dd-10b384f547ca.png)

**Comment by mstem** [comment]
OK, cool. We have the embed code for these, so I'll include the full code in Column N for Stitcher entries, if that works.
