### ISSUE TITLE
Info pane scrollbar missing on MacOS Firefox

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#85]
On Chrome / PC, long listing descriptions get the scrollbar treatment. There's no scrollbar or way to read the rest of the description on MacOS Firefox.
![WhatsApp Image 2020-06-03 at 11 30 31 PM](https://user-images.githubusercontent.com/613432/83691834-284d1e00-a5f3-11ea-8f59-2fbd85a0a6fd.jpeg)

**Comment by jjandoc** [comment]
Note to self: Looks like the scrollbar does show up, but the issue is Firefox is treating the height of the description different than other browsers and not putting enough of a bottom margin below the text to allow the panel to scroll far enough to clear the "watch" button and the white fade right above it.
