### ISSUE TITLE
Width is off on iPad and iPad mini

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#88]
See attachments
![ipad2](https://user-images.githubusercontent.com/613432/83787694-75350100-a694-11ea-9b56-345ccc99d4a5.png)
![ipad](https://user-images.githubusercontent.com/613432/83787700-76662e00-a694-11ea-857d-c5397127d9a5.png)
![ipad mini](https://user-images.githubusercontent.com/613432/83787701-76662e00-a694-11ea-8153-c1bdccd6f846.png)

**Comment by jjandoc** [comment]
Is there a link where I can test this in context? The guide should size to fit the iframe it's embedded in. Judging from the screenshot, I suspect they need to update the width styling of the iframe on their end.

**Comment by mstem** [comment]
Asking

**Comment by jjandoc** [comment]
I'm still seeing this as an issue but I'm not able to debug because boston.com is crashing my ipad. Not just this page, but all of boston.com. The ad tags seem to be doing a number on my device. Still, considering this is operating fine on the Globe, and iframes by design have extremely limited ability to effect its parent page I don't think this is an issue on our side.
