### ISSUE TITLE
Can we design a fall-back solution for Edge (Chromium) users?

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#89]
On Windows, the new version of Edge (based on Chromium engine) stutters instead of scrolls. Could we load the app like we do on mobile, where there is no automatic scroll and the user can just scroll around on their own?

**Comment by jjandoc** [comment]
I actually just picked up a windows machine today and tested on Edge. I'm not seeing what the problem is. The scrolling isn't as smooth as on a Mac, but I suspect that might just be because my Mac is better. I do have an auto scrolling refactor in mind, though, which should boost performance. I'll revisit this once that's been implemented.

**Comment by mstem** [comment]
Was the version of Edge on the Windows machine you used the most recent
update (they switched to the Chromium engine)? Mine is and the scrolling
was stuttering. Now, probably due to a related fix, the page behaves as it
does on mobile (no auto-scrolling). This is an acceptable solution, though
we should then also turn off the auto-selection of listings (which is still
running on Edge) and remove the play/pause button on Edge.

**Comment by jjandoc** [comment]
Play/pause button and infinite scrolling has been removed for Edge.
