### ISSUE TITLE
Can we spin up another app instance for a standalone site?

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#96]
We have green light for a subdomain or custom domain version

**Comment by jjandoc** [comment]
What variations on the existing site would this involve?

**Comment by mstem** [comment]
Identical to the original boston.com paquete other than swapping the
analytics and linking the logo image to bostonglobe.com

**Comment by jjandoc** [comment]
Oh sure, we can do that. Let me know what analytics IDs to swap in. @exafox can you update the Netlify settings to add a branch deploy for "main". I'll set up environment variables and github actions to take care of the rest.

**Comment by jjandoc** [comment]
@mstem I think you mentioned you shared the analytics ID to use somewhere? Can you point me to that or drop it in here so I can finish setting this up?

**Comment by jjandoc** [comment]
Okay, there's a little bit of juggling going on here now with domains since it looks like Netlify wants the associated custom domain name to be for the "primary" site as opposed to a variant, which would've been fine except that our "primary" site is already being used by the Globe. So I've set up a duplicate project in Netlify, except I'm only able to point it to my paquete fork since I don't own the repo. @exafox can you go into the new duplicate project on Netlify at https://app.netlify.com/sites/liveguide/settings/deploys and update the repo so it points to the main project?

**Comment by jjandoc** [comment]
Alright, connected with Stefan. So what I've ended up doing is creating a new project on our Netlify team, `liveguide`. This is so we can use the liveguide.us domain properly and not break the existing paquete.netlify.app embed url.

The last step here is to properly hook up the domain name. For that, @mstem I'll need your help. On the Netlify side, DNS settings can be found here: https://app.netlify.com/teams/stempeck/dns/liveguide.us. The domain name servers need to be updated to point to the netlify hostnames. More documentation can be found here: https://docs.netlify.com/domains-https/netlify-dns/#add-a-domain-you-own. I think the previous CNAME setting updates can be discarded.

Let me know once that's done and I can enforce SSL on the project through Netlify.

**Comment by jjandoc** [comment]
Looks like this is all set. https://www.liveguide.us.

**Comment by mstem** [comment]
Woo! DNS pointed just now, may take 24-48 hours
